### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by poVoq** [Gamer-Kold/Kug#1]
You are baseing this on: https://wolthera.info/2020/12/xmpp-client-in-godot/ ?

Cool idea though, looking forward to try what you come up with!

**Comment by Gamer-Kold** [comment]
Actually I (and the other contributor, TaromaruYuki) wanted to create an XMPP client in Rust for a while now, but haven't found a GUI library that I liked. After I saw how easy it was to just do the GUI in Godot, we just decided to use that instead 💀

**Comment by Gamer-Kold** [comment]
Thanks for the article, though. I hadn't seen that before, I'll use it as reference.
